_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.1
            "8":
                - 5
                - 9
            "12": 0.19.1
            "13": linux-x86_64
backend:
    value: nccl
batch_size:
    value: 256
data_dir:
    value: ./dataset/tiny-imagenet-200
learning_rate:
    value: 0.1
log_interval:
    value: 10
momentum:
    value: 0.9
num_classes:
    value: 200
num_epochs:
    value: 2
num_workers:
    value: 8
pretrained:
    value: false
save_dir:
    value: ./checkpoints
weight_decay:
    value: 0.0001
